### ISSUE TITLE
Global TestCaseCategorization setting function

### ISSUE THREAD

**Issue by Jungyubw** [usnistgov/tcamt#12]

**Comment by Jungyubw** [comment]
1.       Allow users to create list from value sets, independent of any test case, etc.—name and store that list
2.       Allow for the user to select from those list when they select TDC Value-Test Case Fixed List
3.       Allow for global substitution across a message/group/plan
     a.       This is pretty much what we want above 
     b.      Here I create a list (as in 1 in this list)
     c.       Then I select an element (for example, RXA-10.13)
     d.      Then I select a list that gets applied to all instances (in the message/group/plan as selected by the user); Note, only for cases where data is provided.

**Comment by Jungyubw** [comment]
Done. Rob and Sandra,

I will show a demo how to use this, please give me a preferred time.

Thanks.

**Comment by smartinez290** [comment]
Woo -- I want it to QA to this ticket before I leave today. Could you stop by my office and show me?
